// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqJfMeDhAZUziOFaiG8zfwKvC9BRv34rc',
    appId: '1:1042937692864:web:d21ae7ec0d9f85a7cfa325',
    messagingSenderId: '1042937692864',
    projectId: 'foundit-ca10f',
    authDomain: 'foundit-ca10f.firebaseapp.com',
    storageBucket: 'foundit-ca10f.firebasestorage.app',
    measurementId: 'G-CKZCCYEPY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIsWmKL5_3OLCGQbL7sNIrj4CmtHRTmTw',
    appId: '1:1042937692864:android:6731dd3afc8b0b81cfa325',
    messagingSenderId: '1042937692864',
    projectId: 'foundit-ca10f',
    storageBucket: 'foundit-ca10f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC323L2fIBbXSwekYrYDS7JVshUUeZ0pX8',
    appId: '1:1042937692864:ios:ac21074332d73095cfa325',
    messagingSenderId: '1042937692864',
    projectId: 'foundit-ca10f',
    storageBucket: 'foundit-ca10f.firebasestorage.app',
    iosBundleId: 'com.example.foundIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC323L2fIBbXSwekYrYDS7JVshUUeZ0pX8',
    appId: '1:1042937692864:ios:ac21074332d73095cfa325',
    messagingSenderId: '1042937692864',
    projectId: 'foundit-ca10f',
    storageBucket: 'foundit-ca10f.firebasestorage.app',
    iosBundleId: 'com.example.foundIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqJfMeDhAZUziOFaiG8zfwKvC9BRv34rc',
    appId: '1:1042937692864:web:3f255840b665a748cfa325',
    messagingSenderId: '1042937692864',
    projectId: 'foundit-ca10f',
    authDomain: 'foundit-ca10f.firebaseapp.com',
    storageBucket: 'foundit-ca10f.firebasestorage.app',
    measurementId: 'G-930F9BC8BL',
  );
}
